### ISSUE TITLE
Borderless doesn't seem to work

### ISSUE THREAD

**Issue by TheGokki** [PrincessRTFM/AutoMountBGM#2]
~~The plugin doesn't work.~~
~~None of the filters and options seem to do anything.~~
~~I've tried a bunch of mounts, and especially the Borderless music still plays.~~

EDIT: nevermind, it seems to work but only after mounting up... had to do it a few times to make it work it seems. Also, the checkboxes are backwards - it says "Enable mount-specific BGM" but it actually disables it, this is what was confusing me.

EDIT2: the Borderless option doesn't seem to work.

**Comment by TheGokki** [comment]
Borderless doesn't seem to work. ticking or unticking it doesn't prevent the default mount track.

_I'm sorry for all these updates, GitHub doesn't let me delete posts after a mistake._

**Comment by PrincessRTFM** [comment]
I'll look into it after Dawntrail, since there's only a day left before the server maintenance and any update wouldn't be released in time to use.
